# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_roverhead_wrappers", use_symbols = TRUE, package_name = "roverhead")

#' @docType package
#' @usage NULL
#' @useDynLib roverhead, .registration = TRUE
NULL

#' Returns a copy with each element multiplied by two.
#' @export
multiply_copy <- function(doubles) .Call(wrap__multiply_copy, doubles)

#' Multiplies each element by two in place.
#' @export
multiply <- function(doubles) invisible(.Call(wrap__multiply, doubles))

#' Says hello.
hello <- function() invisible(.Call(wrap__hello))

