# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_roverhead_wrappers", use_symbols = TRUE, package_name = "roverhead")

#' @docType package
#' @usage NULL
#' @useDynLib roverhead, .registration = TRUE
NULL

#' Adds two numbers.
#' @export
add <- function(a, b) .Call(wrap__add, a, b)

#' Returns a copy with each element multiplied by two.
#' @export
multiply_by_two_copy <- function(integers) .Call(wrap__multiply_by_two_copy, integers)

