name: Package build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Build source package
        run: R CMD build .
      - name: Build binary package
        run: R CMD INSTALL --build roverhead_0.0.0.9000.tar.gz
